version: "3"
services:
  demo:
    image: quangnhut123/demo-api:latest
    networks:
      - frontend
  guard:
    image: taemon1337/senvoy:1.0.8
    command:
      - "--listen-port"
      - "8443"
      - "--hostname"
      - "guard"
      - "--tls-route"
      - "guard=demo:3000"
      - "--tls-route-domain"
      - "guard=guard:8443"
      - "--tls-route-domain"
      - "guard=proxy"
      - "--tls-route-domain"
      - "guard=proxy:8443"
      - "--tls-route-domain"
      - "guard=snip:8443"
      - "--tls-route-config"
      - "guard=config"
      - "--tls-config-cert"
      - "config=/var/run/envoy/certs/server.crt"
      - "--tls-config-key"
      - "config=/var/run/envoy/certs/server.key"
      - "--tls-config-insecure"
      - "config"
#      - "--allow-san"
#      - "admin.user"
      - "--log"
      - "/dev/stdout"
      - "--log-level"
      - "debug"
    networks:
      - frontend
    depends_on:
      - demo
  proxy:
    image: taemon1337/senvoy:1.0.8
    command:
      - "--listen-port"
      - "8443"
      - "--listen-http-port"
      - "8080"
      - "--hostname"
      - "proxy"
      - "--tls-route"
      - "proxy=guard:8443"
      - "--tls-route-config"
      - "proxy=test"
      - "--tls-upstream-config"
      - "proxy=test"
      - "--tls-route-domain"
      - "proxy=proxy:8443"
      - "--tls-route-domain"
      - "proxy=snip:8443"
      - "--tls-route-domain"
      - "proxy=snip"
      - "--tls-config-cert"
      - "test=/var/run/envoy/certs/server.crt"
      - "--tls-config-key"
      - "test=/var/run/envoy/certs/server.key"
      - "--tls-config-insecure"
      - "test"
      - "--tls-config-upstream-tls"
      - "test"
      - "--tls-config-upstream-sni"
      - "test=guard:8443"
      - "--tls-config-upstream-insecure"
      - "test"
      - "--tls-config-upstream-health-port"
      - "test=8082"
      - "--log"
      - "/dev/stdout"
      - "--log-level"
      - "trace"
    networks:
      - frontend
    depends_on:
      - guard
  snip:
    image: taemon1337/senvoy:1.0.8
    command:
      - "--listen-port"
      - "8443"
      - "--listen-http-port"
      - "8080"
      - "--hostname"
      - "snip"
#      - "--sni-forward-proxy"
#      - "--sni-forward-proxy-port"
#      - "8443"
      - "--http-forward-proxy"
      - "--sni-route"
      - "snip=proxy:8443"
      - "--sni-route-domain"
      - "snip=snip:8443"
      - "--sni-route-domain"
      - "snip=proxy"
      - "--tls-upstream-config"
      - "snip=test"
      - "--tls-config-upstream-health-port"
      - "test=8082"
      - "--log"
      - "/dev/stdout"
      - "--log-level"
      - "trace"
    ports:
      - 80:8080
      - 443:8443
      - 8082:8082
    networks:
      - frontend
    depends_on:
      - proxy
  curler:
    image: curlimages/curl:latest
    command:
      - "/bin/sh"
      - "-c"
      - "while true; do sleep 3600; done"
    networks:
      - frontend
    depends_on:
      - snip
networks:
  frontend:
  backend:
